### ISSUE TITLE
Bug: Cannot find module 'jsonc-parser' after updating to version 3.1.0 from 3.0.1

### ISSUE THREAD

**Issue by lukasoppermann** [amzn/style-dictionary#748]
Hey,
@chazzmoney 

after the update I am getting the following error.
Please let me know if I can provide more helpful information.

If I run `npm i jsonc-parser` the error disappears and it works like a charm

```js
Error: Cannot find module 'jsonc-parser'
Require stack:
- /Users/loppermann/Repos/figma-design-tokens/node_modules/style-dictionary/lib/utils/jsonc.js
- /Users/loppermann/Repos/figma-design-tokens/node_modules/style-dictionary/lib/extend.js
- /Users/loppermann/Repos/figma-design-tokens/node_modules/style-dictionary/index.js
- /Users/loppermann/Repos/figma-design-tokens/node_modules/style-dictionary/bin/style-dictionary
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/loppermann/Repos/figma-design-tokens/node_modules/style-dictionary/lib/utils/jsonc.js:2:15)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/loppermann/Repos/figma-design-tokens/node_modules/style-dictionary/lib/utils/jsonc.js',
    '/Users/loppermann/Repos/figma-design-tokens/node_modules/style-dictionary/lib/extend.js',
    '/Users/loppermann/Repos/figma-design-tokens/node_modules/style-dictionary/index.js',
    '/Users/loppermann/Repos/figma-design-tokens/node_modules/style-dictionary/bin/style-dictionary'
  ]
```

**Comment by lukasoppermann** [comment]
Could it be because it is in the dep dependencies? https://github.com/amzn/style-dictionary/blob/main/package.json#L145

**Comment by equinusocio** [comment]
Same...

**Comment by dbanksdesign** [comment]
The fix has been released on 3.1.1, let me know if you still see the issue!
